version: '2.2'
services:
  web:
    build: .
    command: python3 manager.py
    ports:
      - "8892:8000"
    volumes:
      - ./:/app
    env_file:
      - .env/development/postgres
    depends_on:
      - db

  db:
    image: postgres:14.3
    container_name: db-postgres
    volumes:
      - db_arendator:/var/lib/postgresql/data
    env_file:
      - .env/development/postgres

volumes:
  db_arendator:
